---
  # Clock
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
  # Joint states
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/panda/model/panda/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
  # TF
- ros_topic_name: "/tf"
  gz_topic_name: "/model/panda/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
  # TF static
- ros_topic_name: "/tf_static"
  gz_topic_name: "/model/panda/pose_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
  # Arm Controller Commands
- ros_topic_name: "/arm_controller/commands"
  gz_topic_name: "/model/panda/arm_controller/commands"
  ros_type_name: "std_msgs/msg/Float64MultiArray"
  gz_type_name: "gz.msgs.Double_V"
  direction: ROS_TO_GZ
  # Gazebo RGBD Camera topics
- ros_topic_name: "/rgbd_camera/depth_image"
  gz_topic_name: "/rgbd_camera/depth_image" #"/world/panda/model/rgbd_camera/link/camera_link/sensor/rgbd_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/rgbd_camera/points"
  gz_topic_name: "/rgbd_camera/points" # "/world/panda/model/rgbd_camera/link/camera_link/sensor/rgbd_camera/depth_image/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
- ros_topic_name: "/rgbd_camera/camera_info"
  gz_topic_name: "/rgbd_camera/camera_info" #  "/world/panda/model/rgbd_camera/link/camera_link/sensor/rgbd_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
# added: rgb image
- ros_topic_name: "/rgbd_camera/image"
  gz_topic_name: "/rgbd_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"
